#!/bin/bash -eu

dirs=( docs scripts ush )

echo "=> Formatting code"
ruff format ${dirs[*]}

echo "=> Sorting imports"
ruff check --select I --fix ${dirs[*]}

echo "=> Formatting JSON"
for f in $(find . -not -path "*/.*" -type f -name "*.json" -o -name "*.jsonschema"); do
  jq -S . $f >$f.new || (echo "    in $f" && rm $f.new && false)
  cmp --quiet $f.new $f && rm $f.new || mv $f.new $f
done
