
GFS:
  ics:
    user:
      ics:
        file_templates: "{{ platform.data.gfs.file_templates }}"
        input_file_path: "{{ platform.data.gfs.path }}"
      lbcs:
        file_templates: "{{ platform.data.gfs.file_templates }}"
        input_file_path: "{{ platform.data.gfs.path }}"
    prepare_grib_ics:
      ungrib:
        gribfiles:
          path: "{{ get_lbcs_data.rundir }}/gfs.t{cycle_hour:02d}z.pgrb2.0p25.f{forecast_hour:03d}"
        vtable: "{{ user.mpas_app }}/parm/ungrib/Vtable.GFS"
    create_ics:
      mpas_init:
        namelist:
          update_values:
            dimensions:
              config_nfglevels: 51
              config_nfgsoillevels: 4
  lbcs:
    prepare_grib_lbcs:
      ungrib:
        gribfiles:
          path: "{{ get_ics_data.rundir }}/gfs.t{cycle_hour:02d}z.pgrb2.0p25.f{forecast_hour:03d}"
        vtable: "{{ user.mpas_app }}/parm/ungrib/Vtable.GFS"
    create_lbcs:
      mpas_init:
        namelist:
          update_values:
            dimensions:
              config_nfglevels: 51
              config_nfgsoillevels: 4


RAP:
  ics:
    user:
      ics:
        file_templates: "{{ platform.data.rap.file_templates }}"
        input_file_path: "{{ platform.data.rap.path }}"
    prepare_grib_ics:
      ungrib:
        gribfiles:
          path: '{{ get_lbcs_data.rundir }}/rap.t{cycle_hour:02d}z.wrfnatf{forecast_hour:02d}.grib2'
        vtable: "{{ user.mpas_app }}/parm/ungrib/Vtable.raphrrr"
    create_ics:
      mpas_init:
        namelist:
          update_values:
            dimensions:
              config_nfglevels: 51
              config_nfgsoillevels: 9
  lbcs:
    user:
      lbcs:
        file_templates: "{{ platform.data.rap.file_templates }}"
        input_file_path: "{{ platform.data.rap.path }}"
    prepare_grib_lbcs:
      ungrib:
        gribfiles:
          path: '{{ get_lbcs_data.rundir }}/rap.t{cycle_hour:02d}z.wrfnatf{forecast_hour:02d}.grib2'
        vtable: "{{ user.mpas_app }}/parm/ungrib/Vtable.raphrrr"
    create_lbcs:
      mpas_init:
        namelist:
          update_values:
            dimensions:
              config_nfglevels: 51
              config_nfgsoillevels: 9

