name: Test
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
  workflow_dispatch:
    branches:
      - '**'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        run: make devenv
      - name: Format Check
        run: .github/scripts/format-check.sh
      - name: Test
        run: .github/scripts/test.sh
